### ISSUE TITLE
Autodetect JCL files

### ISSUE THREAD

**Issue by Tam-Lin** [zowe/zlux#438] opened 2020-06-01 14:38 UTC
USS explorer automatically detects REXX execs, but doesn't detect JCL files.  See https://github.com/zowe/explorer-uss/blob/master/WebContent/js/components/editor/Editor.js

**Comment by jordanCain** [comment] 2020-06-02 17:38
Closing as duplicate of https://github.com/zowe/zlux/issues/439 which contains more info

**Closed by jordanCain** 2020-06-02 17:38 UTC
