### ISSUE TITLE
Use JSON web tokens for single sign on

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#224] opened 2019-10-02 19:18 UTC
zLUX needs to accept JSON Web Tokens that originate from either the API Mediation Layer or the ZSS server.

Tokens originating from ZSS:

Replace the current session token with JSON Web Tokens instead. Very little changes from the way things are currently. The logic will remain the same, the function called to generate the string for the token will change.

Tokens originating from the Mediation Layer:

We need to send the username and password to the Mediation Layer so that the JSON Web Token can be generated and given to the browser. Once the token is given to the browser, all subsequent requests to ZSS should include the token such that ZSS can verify the identity of that user.

 

Accpt Criteria:

People are able to log in to the desktop and access any service that is part of Zowe or ZOSMF without having to re authenticate 
Sessions should still expire, today they expire after 60mins 
The users credentials are not multi-casted 
System admin can disable/enable Single SignOn
Constraints

Must not break ability to have multiple instances of Zowe on one system

**Comment by 1000TurquoisePogs** [comment] 2020-05-12 13:44
I'm closing this as it was basically a duplicate of https://github.com/zowe/api-layer/issues/55

**Closed by 1000TurquoisePogs** 2020-05-12 13:44 UTC
Labels: Epic, LTSR, Q1 2020
