### ISSUE TITLE
Problems after installing zowe V1.27

### ISSUE THREAD

**Issue by retrofita** [zowe/zlux#798] opened 2022-01-28 03:30 UTC
After moving from zowe 1.22 to 1.24 to 1.26 which all seemed to have various issues we have installed 1.27 in the hope that it would be more stable.

These are the issues we are experiencing with 1.27

The zowe editor no longer works and returns the following:
![zowe_editor](https://user-images.githubusercontent.com/98559278/151481532-d6502cf3-c003-476d-a6a6-5cfd4e45fa8c.PNG)

IP-explorer gets an internal error:
![ip explorer](https://user-images.githubusercontent.com/98559278/151481648-4459f314-d1ea-4b81-a50f-be53607a6327.PNG)

Workflows are not show:
![workflows](https://user-images.githubusercontent.com/98559278/151481694-94408cb9-658c-4590-a112-0cd70d712621.PNG)

All other apps work fine and as expected. In our previous 1.22 install both the editor and workflows worked fine.

When I activate RBAC all apps become disabled even when I have access to ZLUX.** (I did see another issue for this )

I have the same code on two different sysplex's and are experiencing the same issues.

**Comment by 1000TurquoisePogs** [comment] 2022-01-28 15:54
I tried to follow along your upgrade path but was unable to encounter the issue.
I need some more information to understand what the error 500 is caused by, things such as:

Can you share the job log with me? You shouldn't share it here for sensitivity but you can email me at sgrady@rocketsoftware.com

Can you get to the developer tools in the browser (F12) and within the network tab, when you open the editor or explorer, does the message with a "500" return have a response body that says anything more interesting than "Internal Server Error"?

Are you accessing the desktop via the gateway (aka https://gateway:port/ui/v1/zlux/ZLUX/plugins/org.zowe.zlux.bootstrap/web/) or directly (aka https://app-server:port/ZLUX/plugins/org.zowe.zlux.bootstrap/web/)

Did you make any keystore/keyring changes during the upgrade or not

**Comment by retrofita** [comment] 2022-02-08 06:05
doco sent

**Comment by retrofita** [comment] 2022-02-20 02:29
I am also seeing this in the log:

ZWES1600I JWT will be configured using JWK URL https://xx.xxx.xx.x:7554/gateway/api/v1/auth/keys/public/current   
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds                                    
ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')             
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds                                    
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds                                    
ZWES1606W Failed to get JWK - HTTP response error, retry in 30 seconds                                            
ZWES1602W JWK is in unrecognized format                                                                           
ZWES1605W Server will not accept JWT

These messages are undocumented.

I also turned on loglevel 5 for _zss.jwtTrace but it didn't give me anything extra

any ideas? anyone?

**Comment by lchudinov** [comment] 2022-02-20 06:02
@retrofita Can you please open https://xx.xxx.xx.x:7554/gateway/api/v1/auth/keys/public/current in the browser, then copy and paste the response here.

**Comment by retrofita** [comment] 2022-02-20 20:46
<JSONObject>
<keys>
<kty>RSA</kty>
<e>AQAB</e>
<use>sig</use>
<kid>GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs</kid>
<alg>RS256</alg>
<n>vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ</n>
</keys>
</JSONObject>


Thankyou,

Retrofita

**Comment by cleonty** [comment] 2022-02-21 05:14
The public key looks good to me so I am puzzled  with `ZWES1602W JWK is in unrecognized format`. Can you please try with 
https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.28.0-PR-2677/zowe-1.28.0-pr-2677-1-20220221050102.pax  and show me your zss log. ZSS in the pax has JWK trace enabled.

**Comment by lchudinov** [comment] 2022-02-21 05:18
The public key looks good to me so I am puzzled with `ZWES1602W JWK is in unrecognized format`. Can you please try https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.28.0-PR-2677/zowe-1.28.0-pr-2677-1-20220221050102.pax and copy here the ZSS log. ZSS in the pax has JWK trace enabled.

**Comment by retrofita** [comment] 2022-02-21 23:27
Hi, here is the zss log

ZWES1013I ZSS Server has started. Version '1.27.0+20220220'
ZWES1033I Using server config file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/server.json'
ZWES1038I Server timeouts file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/timeouts.json' either not found or invalid JSON. ZSS sessions will use the default length of one hour.
ZWES1061I TLS settings: keyring '/DHSusrlpp/zowe/keystore/localhost/localhost.keystore.p12', label 'localhost', password '****', stash '(no stash)'
ZWES1101I Product Registration is disabled.
ZWES1035I ZSS Server settings: Address='X.XXX.XX.X', port='8542', protocol='https'
ZWES1063I Caching Service settings: gateway host 'X.XXX.XX.X', port 7554
Plugin=org.zowe.configjs, found 0 data service(s)
Plugin=org.zowe.explorer-ip, found 1 data service(s)
Dataservice: /DHSusrlpp/zowe/runtime/V1R28/components/app-server/share/explorer-ip/lib/ipExplorer.so loaded.
Installing dataservice org.zowe.explorer-ip/ipExplorer to URI /ZLUX/plugins/org.zowe.explorer-ip/services/ipExplorer/**
Plugin=org.zowe.terminal.proxy, found 0 data service(s)
Plugin=org.zowe.terminal.tn3270, found 1 data service(s)
Installing dataservice org.zowe.terminal.tn3270/statediscovery to URI /ZLUX/plugins/org.zowe.terminal.tn3270/services/statediscovery/**
00000000  E9E6C5E2 C9E26DE2 E3C44040 40404040                                      |ZWESIS_STD      |
Plugin=org.zowe.terminal.vt, found 0 data service(s)
Plugin=org.zowe.zlux.agent, found 0 data service(s)
Plugin=org.zowe.zlux.bootstrap, found 0 data service(s)
Plugin=org.zowe.zlux, found 0 data service(s)
Plugin=org.zowe.zlux.ng2desktop, found 0 data service(s)
Plugin=org.zowe.zlux.sample.angular, found 1 data service(s)
Dataservice: /DHSusrlpp/zowe/runtime/V1R28/components/app-server/share/sample-angular-app/lib/storage.so loaded.
Installing dataservice org.zowe.zlux.sample.angular/zssStorage to URI /ZLUX/plugins/org.zowe.zlux.sample.angular/services/zssStorage/**
Plugin=org.zowe.zlux.sample.iframe, found 0 data service(s)
Plugin=org.zowe.zlux.sample.react, found 0 data service(s)
Plugin=org.zowe.zosmf.workflows, found 0 data service(s)
ZWES1600I JWT will be configured using JWK URL https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
ZWES1039I Installing 'VSAM dataset contents' service...
ZWES1039I Installing 'dataset metadata' service...
ZWES1039I Installing 'dataset contents' service...
ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK response: {"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM104E","messageContent":"The endpoint you are looking for '/gateway/api/v1/auth/keys/public/current' could not be located","messageKey":"org.zowe.apiml.common.endPointNotFound"}]}
HTTP status 404
failed to obtain JWK, status = 2
ZWES1606W Failed to get JWK - HTTP response error, retry in 30 seconds
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK response: {"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs","alg":"RS256","n":"vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ"}]}
JWK is not object
ZWES1602W JWK is in unrecognized format
ZWES1605W Server will not accept JWT

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by lchudinov** [comment] 2022-02-22 04:21
Hello,

Thank you for providing the zss log. Can you please try https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.28.0-PR-2677/zowe-1.28.0-pr-2677-2-20220222040325.pax Does it resolve the issue? In any case please paste the zss log here.

Regards,
  Leonty

**Comment by retrofita** [comment] 2022-02-22 05:23
Hi,

No same

ZWES1013I ZSS Server has started. Version '1.27.0+20220221'
ZWES1033I Using server config file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/server.json'
ZWES1038I Server timeouts file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/timeouts.json' either not found or invalid JSON. ZSS sessions will use the default length of one hour.
ZWES1061I TLS settings: keyring '/DHSusrlpp/zowe/keystore/localhost/localhost.keystore.p12', label 'localhost', password '****', stash '(no stash)'
ZWES1101I Product Registration is disabled.
ZWES1035I ZSS Server settings: Address='X.XXX.XX.X', port='8542', protocol='https'
ZWES1063I Caching Service settings: gateway host 'X.XXX.XX.X', port 7554
Plugin=org.zowe.configjs, found 0 data service(s)
Plugin=org.zowe.explorer-ip, found 1 data service(s)
Dataservice: /DHSusrlpp/zowe/runtime/V1R28/components/app-server/share/explorer-ip/lib/ipExplorer.so loaded.
Installing dataservice org.zowe.explorer-ip/ipExplorer to URI /ZLUX/plugins/org.zowe.explorer-ip/services/ipExplorer/**
Plugin=org.zowe.terminal.proxy, found 0 data service(s)
Plugin=org.zowe.terminal.tn3270, found 1 data service(s)
Installing dataservice org.zowe.terminal.tn3270/statediscovery to URI /ZLUX/plugins/org.zowe.terminal.tn3270/services/statediscovery/**
00000000  E9E6C5E2 C9E26DE2 E3C44040 40404040                                      |ZWESIS_STD      |
Plugin=org.zowe.terminal.vt, found 0 data service(s)
Plugin=org.zowe.zlux.agent, found 0 data service(s)
Plugin=org.zowe.zlux.bootstrap, found 0 data service(s)
Plugin=org.zowe.zlux, found 0 data service(s)
Plugin=org.zowe.zlux.ng2desktop, found 0 data service(s)
Plugin=org.zowe.zlux.sample.angular, found 1 data service(s)
Dataservice: /DHSusrlpp/zowe/runtime/V1R28/components/app-server/share/sample-angular-app/lib/storage.so loaded.
Installing dataservice org.zowe.zlux.sample.angular/zssStorage to URI /ZLUX/plugins/org.zowe.zlux.sample.angular/services/zssStorage/**
Plugin=org.zowe.zlux.sample.iframe, found 0 data service(s)
Plugin=org.zowe.zlux.sample.react, found 0 data service(s)
Plugin=org.zowe.zosmf.workflows, found 0 data service(s)
ZWES1600I JWT will be configured using JWK URL https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
ZWES1039I Installing 'VSAM dataset contents' service...
ZWES1039I Installing 'dataset metadata' service...
ZWES1039I Installing 'dataset contents' service...
ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://X.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK response(dump)(contentLength 462, actual 462):
00000000  7B226B65 7973223A 5B7B226B 7479223A  22525341 222C2265 223A2241 51414222 |#.,.`...$#.,.`..................|
00000020  2C227573 65223A22 73696722 2C226B69  64223A22 47557461 4B31596F 58387672 |..............,......../...?....|
00000040  41746C6E 775A442D 346E5035 4F773964  7278622D 74645545 69474D4E 75487322 |..%>.!...>&.|.............(+....|
00000060  2C22616C 67223A22 52533235 36222C22  6E223A22 76417141 744C3246 73687273 |../%............>........<......|
00000080  49595748 34322D4B 4D617774 7A62414C  486C6F2D 61755463 52647278 53626579 |........(/..:..<.%?./..........`|
000000A0  465A614B 31686D71 63727376 434B5957  55464279 5349766B 78683941 2D546F4E |.!/..._............`...,......?+|
000000C0  5A7A325F 53306269 496F4938 32566A6A  56365243 67477842 5158564B 7932317A |!:.^.....?..................`..:|
000000E0  5A2D4F4D 4C594637 55536830 5337386D  4F4C712D 7768374A 5230444E 4E536B49 |!.|(<.........._|<.........++.,.|
00000100  33783163 6F774A4A 592D684E 35714F56  72576964 32464A33 6B724B4E 4E5A4F46 |....?......+..|.........,..++!|.|
00000120  42563579 57464834 6A355970 5F307144  6A58696E 4F354671 4C387574 324B6146 |...`........^......>|...<...../.|
00000140  68586A78 705A7866 65776345 2D587168  72684A6F 774B6A37 33312D53 5A593254 |.....!.............?........!...|
00000160  5342424F 554A686E 4A626871 45364E4D  4F726750 4E42517A 764E6876 35716E45 |...|...>......+(|..&+..:.+....>.|
00000180  496E3137 57713541 6679624C 4349346E  69346E55 73335034 512D7556 6972634A |.>.......`.<...>..>...&.........|
000001A0  754D4647 58303146 6B4C3932 31536832  4C78456F 30684B36 50414A48 546C2D75 |.(......,<......<..?....&....%..|
000001C0  564B6677 346A4D35 4551227D 5D7D                                          |......(....')'|
JWK response: {"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs","alg":"RS256","n":"vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ"}]}
JSON parsed:
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs",
      "alg": "RS256",
      "n": "vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ"
    }
  ]
}
JWK is not object
ZWES1602W JWK is in unrecognized format
ZWES1605W Server will not accept JWT

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by lchudinov** [comment] 2022-02-22 07:06
Hi,

Thank you for giving a try to the pax. Now I have a clue. I've made a new pax https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/1.28.0-PR-2677/zowe-1.28.0-pr-2677-3-20220222064258.pax that should fix the issue. Can you please try it.

Regards,
  Leonty

**Comment by retrofita** [comment] 2022-02-22 09:38
Hi Leonty,

That looks better, I get the right message at the end.

When I start zowe and view the applications I only see the following:

***@***.***

ZWES1013I ZSS Server has started. Version '1.27.0+20220222'
ZWES1033I Using server config file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/server.json'
ZWES1038I Server timeouts file '/DHSusrlpp/zowe/instance/ZWE1/workspace/app-server/serverConfig/timeouts.json' either not found or invalid JSON. ZSS sessions will use the default length of one hour.
ZWES1061I TLS settings: keyring '/DHSusrlpp/zowe/keystore/localhost/localhost.keystore.p12', label 'localhost', password '****', stash '(no stash)'
ZWES1101I Product Registration is disabled.
ZWES1035I ZSS Server settings: Address='XX.XXX.XX.X', port='8542', protocol='https'
ZWES1063I Caching Service settings: gateway host 'XX.XXX.XX.X', port 7554
Plugin=org.zowe.configjs, found 0 data service(s)
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/zlux-editor/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/zlux-editor/pluginDefinition.json''
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/explorer-ip/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/explorer-ip/pluginDefinition.json''
Plugin=org.zowe.terminal.proxy, found 0 data service(s)
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/tn3270-ng2/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/tn3270-ng2/pluginDefinition.json''
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/vt-ng2/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/vt-ng2/pluginDefinition.json''
Plugin=org.zowe.zlux.agent, found 0 data service(s)
Plugin=org.zowe.zlux.bootstrap, found 0 data service(s)
Plugin=org.zowe.zlux, found 0 data service(s)
Plugin=org.zowe.zlux.ng2desktop, found 0 data service(s)
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-angular-app/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-angular-app/pluginDefinition.json''
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-iframe-app/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-iframe-app/pluginDefinition.json''
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-react-app/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/sample-react-app/pluginDefinition.json''
ZWES1006E Error while parsing file '/DHSusrlpp/zowe/runtime/current/components/app-server/share/zlux-workflow/pluginDefinition.json': 'Couldn't open '/DHSusrlpp/zowe/runtime/current/components/app-server/share/zlux-workflow/pluginDefinition.json''
ZWES1600I JWT will be configured using JWK URL https://XX.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK request to https://XX.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
ZWES1039I Installing 'VSAM dataset contents' service...
ZWES1039I Installing 'dataset metadata' service...
ZWES1039I Installing 'dataset contents' service...
ZWES1014I ZIS status - 'Ok' (name='ZWESIS_STD      ', cmsRC='0', description='Ok', clientVersion='2')
JWK request to https://XX.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://XX.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
error initing session: 6
failed to obtain JWK, status = 9
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
JWK request to https://XX.XXX.XX.X:7554/gateway/api/v1/auth/keys/public/current
JWK response(dump)(contentLength 462, actual 462):
00000000  7B226B65 7973223A 5B7B226B 7479223A  22525341 222C2265 223A2241 51414222 |#.,.`...$#.,.`..................|
00000020  2C227573 65223A22 73696722 2C226B69  64223A22 47557461 4B31596F 58387672 |..............,......../...?....|
00000040  41746C6E 775A442D 346E5035 4F773964  7278622D 74645545 69474D4E 75487322 |..%>.!...>&.|.............(+....|
00000060  2C22616C 67223A22 52533235 36222C22  6E223A22 76417141 744C3246 73687273 |../%............>........<......|
00000080  49595748 34322D4B 4D617774 7A62414C  486C6F2D 61755463 52647278 53626579 |........(/..:..<.%?./..........`|
000000A0  465A614B 31686D71 63727376 434B5957  55464279 5349766B 78683941 2D546F4E |.!/..._............`...,......?+|
000000C0  5A7A325F 53306269 496F4938 32566A6A  56365243 67477842 5158564B 7932317A |!:.^.....?..................`..:|
000000E0  5A2D4F4D 4C594637 55536830 5337386D  4F4C712D 7768374A 5230444E 4E536B49 |!.|(<.........._|<.........++.,.|
00000100  33783163 6F774A4A 592D684E 35714F56  72576964 32464A33 6B724B4E 4E5A4F46 |....?......+..|.........,..++!|.|
00000120  42563579 57464834 6A355970 5F307144  6A58696E 4F354671 4C387574 324B6146 |...`........^......>|...<...../.|
00000140  68586A78 705A7866 65776345 2D587168  72684A6F 774B6A37 33312D53 5A593254 |.....!.............?........!...|
00000160  5342424F 554A686E 4A626871 45364E4D  4F726750 4E42517A 764E6876 35716E45 |...|...>......+(|..&+..:.+....>.|
00000180  496E3137 57713541 6679624C 4349346E  69346E55 73335034 512D7556 6972634A |.>.......`.<...>..>...&.........|
000001A0  754D4647 58303146 6B4C3932 31536832  4C78456F 30684B36 50414A48 546C2D75 |.(......,<......<..?....&....%..|
000001C0  564B6677 346A4D35 4551227D 5D7D                                          |......(....')'|
JWK response: {"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs","alg":"RS256","n":"vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ"}]}
JSON parsed:
{
  "keys": [
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "GUtaK1YoX8vrAtlnwZD-4nP5Ow9drxb-tdUEiGMNuHs",
      "alg": "RS256",
      "n": "vAqAtL2FshrsIYWH42-KMawtzbALHlo-auTcRdrxSbeyFZaK1hmqcrsvCKYWUFBySIvkxh9A-ToNZz2_S0biIoI82VjjV6RCgGxBQXVKy21zZ-OMLYF7USh0S78mOLq-wh7JR0DNNSkI3x1cowJJY-hN5qOVrWid2FJ3krKNNZOFBV5yWFH4j5Yp_0qDjXinO5FqL8ut2KaFhXjxpZxfewcE-XqhrhJowKj731-SZY2TSBBOUJhnJbhqE6NMOrgPNBQzvNhv5qnEIn17Wq5AfybLCI4ni4nUs3P4Q-uVircJuMFGX01FkL921Sh2LxEo0hK6PAJHTl-uVKfw4jM5EQ"
    }
  ]
}
ZWES1601I Server is ready to accept JWT with fallback to legacy tokens

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by retrofita** [comment] 2022-02-22 09:51
I have attached the zowe joblog which has the ‘failed to load’ messages at the end

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by lchudinov** [comment] 2022-02-22 10:11
> I have attached the zowe joblog which has the ‘failed to load’ messages at the end

I couldn't find `failed to load` in the log. Can you please check if it wasn't truncated.

**Comment by retrofita** [comment] 2022-02-22 20:26
I had a look at the attachment and see many of these sorts of messages towards the bottom for various applications:


2022-02-22 19:38:05.682 <ZWED:84019177> ZWESVUSR INFO (_zsf.bootstrap,plugin-loader.js:759) Failed to load org.zowe.editor.json
2022-02-22 19:38:05.682 <ZWED:33687595> ZWESVUSR INFO (_zsf.bootstrap,plugin-loader.js:759) Failed to load org.zowe.editor.json

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by retrofita** [comment] 2022-02-22 20:40
Hi Leonty,

I compared this latest runtime that you provided (V1R28) and my original one (V1R27) and can see some directories missing. I’ll get it down again in case there was an issue with the download.

***@***.***

***@***.***

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by retrofita** [comment] 2022-02-22 21:07
Hi Leonty,

I redid the unpax and install and can now see the missing directories. I recreated my instance and started zowe. I now can now see all applications and they all start as expected:

***@***.***

What is the next step. Can I use this pax you provided or will I need to get down another release?


Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by cleonty** [comment] 2022-02-24 10:49
Hi Ted,

The fix is going be included in `1.28`. You can use the pax that I sent while `1.28` hasn't released.

Regards,
  Leonty

**Comment by lchudinov** [comment] 2022-02-24 10:52
Hi Ted,

The fix is going to be included in `1.28`. You can use the pax that I provided while `1.28` hasn't released.

Regards,
  Leonty

**Comment by retrofita** [comment] 2022-02-24 22:30
Hi Leonty,

Thankyou for your help.

Regards,
Ted Hempstead

Mainframe Engineering Services
Infrastructure Platforms Branch
Infrastructure and Operations Division
[Title: Services Australia branding - Description: Services Australia servicesaustralia.gov.au]
Level 2 Main Building, 134 Reed St, Greenway ACT 2900
Phone: 02 6191 9250  (Ext. 609250)

**Comment by lchudinov** [comment] 2022-02-25 07:03
Hi Ted,

Glad to hear that the pax works for you. I close this issue. Please open a new one if you experience any issue.

Regards,
  Leonty

**Closed as completed by lchudinov** 2022-02-25 07:03 UTC
