### ISSUE TITLE
zowe 2.0 on zOS: After zowe logon. Opening Jes Explorer prompts for userid and logon and getting Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Sathya755** [zowe/zlux#863] opened 2022-06-02 10:39 UTC
**Describe the bug**
Hi Team,
We have recently installed Zowe 2.0 successfully on zOS.
We are able to use Zowe Desktop at https://myhost:httpsPort/ and logon successfully.
After logon selecting any option, say for eg. Jes Explorer prompts for userid and logon and getting Unexpected token < in JSON at position 0 after providing valid userid and password.

Can you please check and suggest.
Please let me know if you need any other details.

Regards,
Sathya

 

**Screenshots**

![zowe error](https://user-images.githubusercontent.com/79004351/171612132-3f1a2ade-f377-4c1b-8f5d-70d4fd8e638b.JPG)

**Comment by 1000TurquoisePogs** [comment] 2022-07-07 14:09
When using the explorers, please access the Desktop from the gateway, https://myhost:httpsPort/zlux/ui/v1/

**Comment by GilPen** [comment] 2022-09-02 13:26
Hello 

Did you find the answer to your question ? 

I have the same issue and I'd like to correct it.

And when I access from the gateway https://host:port/zlux/ui/v1

The answer is 
{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM104E","messageContent":"The endpoint you are looking for '/ZLUX/ui/v1' could not be located","messageAction":"Verify that the URL of the endpoint you are trying to reach is correct.","messageReason":"The endpoint you are looking for could not be located.","messageKey":"org.zowe.apiml.common.endPointNotFound"}]}

**Comment by 1000TurquoisePogs** [comment] 2022-09-23 13:51
You must use lowercase, it's https://myhost:httpsPort/zlux/ui/v1/ not https://myhost:httpsPort/ZLUX/ui/v1/

**Comment by DivergentEuropeans** [comment] 2022-12-06 01:56
Correction @GilPen, may not have been obvious from @1000TurquoisePogs 's answer but the "httpsPort" in:
https://myhost:httpsPort/zlux/ui/v1/

is referring to the Gateway port. So please make sure you trying with the Gateway port, not the App server port. Once accessed the Desktop from the Gateway, you can click on the Explorers and they should work as intended now

**Comment by DivergentEuropeans** [comment] 2022-12-06 01:58
As @1000TurquoisePogs linked, he's working on making that redirect happen automatically so there's less future confusion

**Comment by 1000TurquoisePogs** [comment] 2024-11-05 12:39
Closing as resolved by documentation and redirect
https://docs.zowe.org/stable/user-guide/mvd-using#accessing-the-zowe-desktop states the correct URL to get to the desktop in order to have the JES explorers working.
The app server attempts to automatically put you on the correct URL via redirect.

**Closed as completed by 1000TurquoisePogs** 2024-11-05 12:39 UTC
Labels: bug
