### ISSUE TITLE
Edge UI issues

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#73] opened 2019-02-15 13:41 UTC
This ticket contains Microsoft Edge UI issues.
Chrome browser is considered the standard. UI parts that looks in Edge different than in Chrome will be described here.

1. Main menu scrollbar - sharp corner instead of round. 
2. Lower right corner of Parameters field in IFrame application can not be dragged. So we can't resize Parameter field.
3. Some mess with display of dates and time in the lower right corner of MVD.

**Comment by DivergentEuropeans** [comment] 2020-04-03 00:12
1. Microsoft made it such that the scrollbar is unchangeable by design. See: https://answers.microsoft.com/en-us/windows/forum/windows_10-start/how-to-change-the-microsoft-edge-scrollbar-color/a60d8a52-3e80-4ecc-b0d3-bd14293382b6

2. This is no longer a thing because I redid the Iframe Sample App last year

3. This is no longer a thing because I cannot replicate it 

Not to mention, Edge released in January now runs on Chromium and will not have these problems... Closing ticket

**Closed by DivergentEuropeans** 2020-04-03 00:12 UTC
Labels: backlog, bug
