### ISSUE TITLE
When logging in with the incorrect password via Desktop the call happens more than once

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zlux#718] opened 2021-06-21 09:50 UTC
**Describe the bug**
The desktop configured with providers saf, apiml and zss lock out the user when providing an incorrect password. It's on the system where three incorrect calls result in the lock of the user account. 

**Steps to Reproduce**

1. Go to the ZLUX desktop login page
2. Provide valid username and invalid credentials
3. Provide the same username with valid credentials

**Expected behavior**
Login into the system. 

The actual behavior is that the user isn't logged in. 

**Details**
 - Version and build number: v. 1.19.0+20210121
 - Test environment: Sysplex, TSS

**Web Browser Details (if the bug relates to Zowe Desktop usage):**
 - OS: Windows
 - Browser Firefox

**Additional context**

**Comment by 1000TurquoisePogs** [comment] 2021-08-27 13:46
I believe this only happens when you're not using SSO. non-SSO config takes the user credentials typed in the browser and sends them to both zss and apiml. apiml then could send to zosmf. So, you can end up with multiple auth attempts.
If we're seeing more than 2 in total though, there could be a bug somewhere, since i only count 2 (zss+apiml)

**Comment by 1000TurquoisePogs** [comment] 2021-08-27 13:49
We could start by turning on debug logging in ZIS for safVerify calls such as these https://github.com/zowe/zss/blob/staging/c/zis/services/auth.c#L119 in order to detect when login attempts occur there.
But we'll need to do the same for apiml & zosmf if we want to get the big picture.

**Comment by 1000TurquoisePogs** [comment] 2022-04-15 12:53
Closing as a duplicate of https://github.com/zowe/zlux/issues/761

**Closed as completed by 1000TurquoisePogs** 2022-04-15 12:53 UTC
